# Minimal ModSecurity config for prototype
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyInMemoryLimit 131072

# Use OWASP CRS rules path
Include /etc/nginx/rules/*.conf

# Basic actions
SecDefaultAction "phase:2,deny,log"
