user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log  /var/log/nginx/access.log;

    sendfile        on;
    keepalive_timeout  65;

    # WAF: Ẩn thông tin phiên bản Nginx để tránh bị dò quét lỗ hổng
    server_tokens off;

    # WAF: Giới hạn dung lượng request (ngăn chặn upload file rác khổng lồ gây đầy ổ cứng)
    client_max_body_size 5M;

    # WAF: Cấu hình Rate Limiting (Chống Spam / DDoS)
    # Tạo một vùng nhớ tên là 'mylimit', dung lượng 10MB để lưu trạng thái IP
    # Giới hạn tối đa: 5 request / 1 giây cho mỗi IP
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/s;

    server {
        listen 80;
        server_name _;

        # WAF: Bật Rate Limit cho toàn bộ Server
        # burst=10: Cho phép "vượt rào" tối đa 10 request cùng lúc (để load trang không bị lỗi)
        # nodelay: Báo lỗi 503 ngay lập tức nếu vượt quá (không bắt người dùng chờ)
        limit_req zone=mylimit burst=10 nodelay;

        include /etc/nginx/blocked_ips.conf;

        location /lb-health {
            proxy_pass http://load-balancer/lb-health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/secure/ {
            proxy_pass http://load-balancer/api/secure/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/vuln/ {
            proxy_pass http://load-balancer/api/vuln/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /admin/ {
            proxy_pass http://127.0.0.1:8080/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}